### ISSUE TITLE
v1.2.0 Checklist

### ISSUE THREAD

**Issue by le717** [le717/LDR-Importer#20]
Targets for version 1.2.0. Items can be pushed back if needed.
- [x] Add "Spaces between bricks" import option (92d510f30294032ccb8bf552c51ae1e77e05a1cc)
- [x] Beta support of LSynth bendable parts (#79) 
- [x] v1.1.5 is five times slower (#61, #73)
- [x] Add operator presets to save import settings (#42, #65)
- [x] Import options for spaces between bricks for added realism (92d510f)
- [x] Any open issues for [this milestone](https://github.com/le717/LDR-Importer/issues?milestone=3&state=open)

**Comment by posfan12** [comment]
Did MPD support make it in?

**Comment by le717** [comment]
@posfan12 No, MPD support has not been added and is currently not being worked on. There are technical issues preventing us from ever considering MDP support right now. Sorry. :(

**Comment by posfan12** [comment]
If MPD support did exist, what would the result be? A single file or multiple files? I'm new to Blender and don't know how it works.
