### ISSUE TITLE
v2.0.0 Beta 1 Checklist

### ISSUE THREAD

**Issue by le717** [le717/LDR-Importer#41]
Targets for version 2.0.0 Beta 1. Items can be pushed back if needed.

#### Merged from #60: ####
- [ ] Implement Optional lines
- [ ] Add back clean-up options
- [x] Apply transformations as necessary (scale set by user on import, and rotation to match blender's coordinate system)
- [ ] Implement materials (make a dict mapping colour indices to `bpy.types.Material`s in the `LDrawParser` class?)
- [x] Guess library path
- [x] Search appropriate paths according to chosen LoD
- [ ] Handle incorrectly-formatted lines properly
- [ ] Think about how to catch circular references

- [ ] Any open issues for [this milestone](https://github.com/le717/LDR-Importer/issues?milestone=2&state=open)
