### ISSUE TITLE
v1.1 Checklist

### ISSUE THREAD

**Issue by le717** [le717/LDR-Importer#5]
Targets for version 1.1. Items can be pushed back if needed.
- [x] ~~Load preset upon startup~~ (Can not be done; Blender does not support it; no longer needed; see #30)
- [x] Set each brick's origin to geometry - Added in a4f4ee68fa1a4fa83987092719697be80ed3c4e2
- [x] Metallic colors
- [x] Support for "redirect bricks" (see #10)
- [x] ~~Skip (or gracefully handle and display error message as a quick patch) non-existent bricks.~~ (Delayed for a later release due to script issues, workaround applied in the meantime; see #11)
- [x] Blender for Mac OS X and Linux support ([patch submitted](http://sourceforge.net/u/le717/forum/bugs/thread/bf67c635/), never worked. See also #13, added in #14)
- [x] Better installation instructions (mention installing straight from the `.zip` archive) and Readme overall
- [x] Any open issues for [this milestone](https://github.com/le717/Blender-2.6-LDraw-Importer/issues?milestone=1&state=open)
