### ISSUE TITLE
v1.1.5 Checklist

### ISSUE THREAD

**Issue by le717** [le717/LDR-Importer#53]
Targets for version 1.1.5. Items can be pushed back if needed.
#### v1.1.5 is more of a intermediate release to provide bug fixes and patches for v1.1 and tide users over until v1.2.
- [x] Always save `config.py` in user's `AppData` on Windows (#38)
- [x] Remove Video Game Cleanup option (#47)
- [x] Better part path searching (#50, https://github.com/le717/LDR-Importer/issues/40#issuecomment-31278726, https://github.com/le717/LDR-Importer/issues/40#issuecomment-31279788)
- [x] UCS-2 BE & LE model encoding breaks script (https://github.com/le717/LDR-Importer/issues/36#issuecomment-31066960, #37)
- [x] Fix tooltips on import settings to be clearer
- [x] Give unofficial files precedence over official ones; correct usage of p/8 primitives folder (#52, #54)
- [x] Global variable "paths" overflows (#55)
- [x] Make mention of [MPDCenter](http://ldraw.heidemann.org/index.php?page=mpdcenter) in Readme to workaround lack of MPD support
- [x] Multiple edge split modifiers from `CleanUp` added to single brick (#57)
- [x] Any other open issues for [this milestone](https://github.com/le717/LDR-Importer/issues?milestone=5&state=open)
