### ISSUE TITLE
v1.3.0 Checklist

### ISSUE THREAD

**Issue by le717** [le717/LDR-Importer#88]
_This list is incomplete!_

- [ ]  Add bevel import option (#83) 
- [x] Align scale factor with LeoCAD (#93)
- [x] Remove change log from Readme.html, point to Wiki
- [x] Link alike (model + color) mesh ([feature request](http://sourceforge.net/u/le717/forum/general/thread/20049a5b/), PR #100)
- [x] Implement new preferences system (#101)
- [x] Implement some of rioforce's new Cycles materials (#102)
- [x] Support direct colors (#63)
- [x] Do not duplicate materials (#92)
- [x] Drop non-UTF-8 file encoding support (#104)

**Comment by le717** [comment]
I forget why I was even making this list. Milestones do this job better.
